// actionTypes.js
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const REMOVE_ACCESS_TOKEN = "REMOVE_ACCESS_TOKEN"

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';

export const ADD_TO_WISH = 'ADD_TO_WISH';
export const REMOVE_FROM_WISH = 'REMOVE_FROM_WISH';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const CLEAR_CART = 'CLEAR_CART';

export const SET_ORDER_ID = 'SET_ORDER_ID';
export const CLEAR_ORDER_ID = 'CLEAR_ORDER_ID';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
